apiVersion: v1
kind: Service
metadata:
  name: orderer1-orderer
spec:
  selector:
    app.kubernetes.io/name: orderer1-orderer
  ports:
    - name: orderer-listenport
      port: 7121
      protocol: TCP
      targetPort: 7121
