apiVersion: v1
kind: Service
metadata:
  name: orderer2-orderer
spec:
  selector:
    app.kubernetes.io/name: orderer2-orderer
  ports:
    - name: orderer-listenport
      port: 7122
      protocol: TCP
      targetPort: 7122
