apiVersion: v1
kind: Service
metadata:
  name: orderer3-orderer
spec:
  selector:
    app.kubernetes.io/name: orderer3-orderer
  ports:
    - name: orderer-listenport
      port: 7123
      protocol: TCP
      targetPort: 7123
