apiVersion: v1
kind: Service
metadata:
  name: ca-intermediate
spec:
  selector:
    app.kubernetes.io/name: ca-intermediate
  ports:
    - name: api
      port: 7131
      targetPort: 7131
      protocol: TCP