apiVersion: v1
kind: Service
metadata:
  name: peer2-peer
spec:
  selector:
    app.kubernetes.io/name: peer2-peer
  ports:
    - name: chaincode
      port: 7052
      protocol: TCP
      targetPort: 7052
    - name: peer-listenport
      port: 7102
      protocol: TCP
      targetPort: 7102
